# -*- mode: ruby -*- 
# vi: set ft=ruby : 
# Every Vagrant development environment requires a box. You can search for 
# boxes at https://atlas.hashicorp.com/search. 
BOX_IMAGE = "ubuntu/bionic64" #기존 우분투 박스 
NODE_COUNT = 2 #총 노드 개수, 2일 경우 master 1개 worker 2개가 생성된다

Vagrant.configure("2") do |config|
  config.vm.define "master1" do |node|     
    node.vm.box = BOX_IMAGE
    node.vm.hostname = "master1"
    node.vm.network "private_network", ip: "172.20.0.100"  
  end

  (1..NODE_COUNT).each do |i|     
    config.vm.define "worker#{i}" do |node|
      node.vm.box = BOX_IMAGE
      node.vm.hostname = "worker#{i}"
      node.vm.network "private_network", ip: "172.20.0.#{i + 100}"
    end

  end 

end
